apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
      external_labels:
        cluster: 'aks-kong-cluster'
        environment: 'production'

    # Alertmanager設定 (必要に応じて設定)
    # alerting:
    #   alertmanagers:
    #   - static_configs:
    #     - targets:
    #       - alertmanager:9093

    # ルールファイル (必要に応じて設定)
    # rule_files:
    #   - "alerts/*.yml"

    scrape_configs:
      # Prometheus自身のメトリクス
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      # Kong Admin APIからのメトリクス収集
      - job_name: 'kong-admin'
        metrics_path: '/metrics'
        static_configs:
          - targets: ['kong-admin.kong.svc.cluster.local:8001']
        relabel_configs:
          - source_labels: [__address__]
            target_label: instance
          - target_label: job
            replacement: kong-admin

      # Kong Statusエンドポイントからのメトリクス収集
      - job_name: 'kong-status'
        metrics_path: '/metrics'
        static_configs:
          - targets: ['kong-metrics.kong.svc.cluster.local:8100']
        relabel_configs:
          - source_labels: [__address__]
            target_label: instance
          - target_label: job
            replacement: kong-status

      # Kubernetes Service Discoveryを使用したKong Podの自動検出
      - job_name: 'kong-pods'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - kong
        relabel_configs:
          # Prometheusアノテーションが設定されているPodのみをスクレイプ
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: kubernetes_pod_name
