# ワークフローの名前: DockerHubのKong GatewayイメージをGitHub Container Registry (GHCR) に再プッシュ
name: Push Kong Gateway Image to GHCR

# このワークフローが実行されるタイミングを定義
on:
  # GitHub UI から手動でトリガーのみ
  workflow_dispatch:  # GitHub UI から手動でトリガー可能

# 環境変数の設定
env:
  REGISTRY: ghcr.io  # GitHub Container Registry のURL
  IMAGE_NAME: ${{ github.repository }}/kong-gateway  # イメージ名（リポジトリ名に基づく）

# ジョブの定義
jobs:
  # DockerHubからイメージをプルしてGHCRに再プッシュするジョブ
  pull-and-push:
    # Ubuntuの最新バージョン上で実行
    runs-on: ubuntu-latest
    # 必要な権限の設定
    permissions:
      packages: write  # GitHubパッケージ（コンテナイメージ）を書き込む権限

    # 実行する一連のステップ
    steps:
      # ステップ1: GitHub Container Registryにログイン
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}  # レジストリのURL（ghcr.io）
          username: ${{ github.actor }}  # 現在のユーザー名（ワークフローを実行したユーザー）
          password: ${{ secrets.GITHUB_TOKEN }}  # GitHubが自動的に提供する認証トークン

      # ステップ2: DockerHubからKong Gatewayイメージをプル
      - name: Pull Kong Gateway from DockerHub
        run: |
          # Kong Gatewayの最新バージョンとタグ付きバージョンをプル
          docker pull kong/kong-gateway:latest
          docker pull kong/kong-gateway:3.4.1  # 必要に応じて特定のバージョンを指定

      # ステップ3: イメージにGHCR用のタグを付ける
      - name: Tag images for GHCR
        run: |
          # GHCRのURLとリポジトリ名を使ってタグ付け
          docker tag kong/kong-gateway:latest ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          docker tag kong/kong-gateway:3.4.1 ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:3.4.1
      
      # ステップ4: GHCRにイメージをプッシュ
      - name: Push images to GHCR
        run: |
          # タグ付けしたイメージをGHCRにプッシュ
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:3.4.1
