name: Scan Kong Gateway Image

on:
  # 別のワークフロー(Push Kong Gateway Image to GHCR)が完了した後に実行
  workflow_run:
    workflows: ["Push Kong Gateway Image to GHCR"]
    types:
      - completed
  workflow_dispatch: # 手動トリガーも可能

env:
  REGISTRY: ghcr.io # GitHubのコンテナレジストリのURL
  IMAGE_NAME: api-pf/kong-bootcamp/kong-gateway # スキャン対象のイメージ名（小文字のみ）

jobs:
  scan-image:
    runs-on: ubuntu-latest
    # workflow_runイベントの場合は前のワークフローが成功した場合のみ実行
    # workflow_dispatchイベント（手動実行）の場合は常に実行
    if: >-
      github.event_name == 'workflow_dispatch' || 
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    permissions:
      # contents: read # リポジトリのコンテンツを読み取る権限
      packages: read # GitHubパッケージ（コンテナイメージ）を読み取る権限
      # security-events: write # セキュリティスキャン結果をGitHubセキュリティタブに書き込む権限
      # id-token: write # OIDC認証のために必要
      actions: read # ワークフロー実行の情報へのアクセス権

    # 実行する一連のステップ
    steps:
      # # リポジトリのコードをチェックアウト
      # - name: Checkout repository
      #   uses: actions/checkout@v4

      # GitHub Container Registryにログイン
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }} # レジストリのURL（ghcr.io）
          username: ${{ github.actor }} # 現在のユーザー名（ワークフローを実行したユーザー）
          password: ${{ secrets.GITHUB_TOKEN }} # GitHubが自動的に提供する認証トークン

      # スキャン対象のKong Gatewayイメージをプル
      - name: Pull Kong Gateway image
        run: |
          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ vars.KONG_VER }}

      # スキャン
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ vars.KONG_VER }}" # スキャン対象のイメージ
          format: "table"
          severity: "CRITICAL,HIGH" # 重要度が「重大」と「高」の脆弱性のみをスキャン
