# ワークフローの名前: Kong Gateway イメージのセキュリティスキャン
name: Scan Kong Gateway Image

# このワークフローが実行されるタイミングを定義
on:
  # 別のワークフロー(Push Kong Gateway Image to GHCR)が完了した後に実行
  workflow_run:
    workflows: ["Push Kong Gateway Image to GHCR"]
    types:
      - completed
  # GitHub上の「Actions」タブから手動で実行可能
  workflow_dispatch:  # 手動トリガーも可能

# 環境変数の設定
env:
  REGISTRY: ghcr.io  # GitHubのコンテナレジストリのURL
  IMAGE_NAME: api-pf/kong-bootcamp/kong-gateway  # スキャン対象のイメージ名（小文字のみ）

# ジョブの定義
jobs:
  # イメージスキャンジョブ
  scan-image:
    # Ubuntuの最新バージョン上で実行
    runs-on: ubuntu-latest
    # トリガーに応じた条件分岐
    # workflow_runイベントの場合は前のワークフローが成功した場合のみ実行
    # workflow_dispatchイベント（手動実行）の場合は常に実行
    if: >-
      github.event_name == 'workflow_dispatch' || 
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    # 必要な権限の設定
    permissions:
      contents: read       # リポジトリのコンテンツを読み取る権限
      packages: read       # GitHubパッケージ（コンテナイメージ）を読み取る権限
      security-events: write  # セキュリティスキャン結果をGitHubセキュリティタブに書き込む権限
      id-token: write      # OIDC認証のために必要
      actions: read        # ワークフロー実行の情報へのアクセス権

    # 実行する一連のステップ
    steps:
      # ステップ1: リポジトリのコードをチェックアウト（Dockerfileなどを利用するため）
      - name: Checkout repository
        uses: actions/checkout@v4

      # ステップ2: GitHub Container Registryにログイン
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}  # レジストリのURL（ghcr.io）
          username: ${{ github.actor }}  # 現在のユーザー名（ワークフローを実行したユーザー）
          password: ${{ secrets.GITHUB_TOKEN }}  # GitHubが自動的に提供する認証トークン
      
      # ステップ3: スキャン対象のKong Gatewayイメージをプル
      - name: Pull latest image
        run: |
          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      # ステップ4: Trivyを使用した脆弱性スキャン
      # Trivyは、オープンソースの軽量コンテナスキャナー
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest'  # スキャン対象のイメージ
          format: 'sarif'  # GitHub Security Dashboardで表示するためのフォーマット
          output: 'trivy-results.sarif'  # 結果の出力先ファイル
          severity: 'CRITICAL,HIGH'  # 重要度が「重大」と「高」の脆弱性のみをスキャン

      # ステップ5: Trivyのスキャン結果をGitHub Security Insightsにアップロード
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'  # Trivyの結果ファイル
          category: 'trivy-scan'  # 結果をカテゴリ分けするためのラベル

      # ステップ6: Snykを使用した追加の脆弱性スキャン
      # Snykは、より詳細な脆弱性分析と継続的なモニタリング機能を提供
      - name: Scan with Snyk
        uses: snyk/actions/docker@master
        # Snykの実行は任意（トークンが設定されていない場合は実行しない）
        continue-on-error: true
        env:
          # Snykの認証トークン（GitHub Secretsに設定する必要あり）
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest  # スキャン対象のイメージ
          args: --file=Dockerfile  # Dockerfile参照してコンテキスト情報を取得
          # エラーが発生しても続行
          continue-on-error: true
          # SARIFレポート形式を有効化
          sarif: true

      # ステップ7: Snykのスキャン結果をGitHub Security Insightsにアップロード
      # Snyk結果ファイルが存在する場合のみ実行
      - name: Upload Snyk scan result
        uses: github/codeql-action/upload-sarif@v3
        if: ${{ success() && hashFiles('snyk.sarif') != '' }}
        with:
          sarif_file: snyk.sarif  # Snykの結果ファイル
          category: 'snyk-scan'  # 結果をカテゴリ分けするためのラベル
