name: Scan Kong Gateway Image

on:
  workflow_run:
    workflows: ["Push Kong Gateway Image to GHCR"]
    types:
      - completed
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: api-pf/kong-bootcamp/kong-gateway

jobs:
  scan-image:
    runs-on: ubuntu-latest
    # workflow_runイベントの場合は前のワークフローが成功した場合のみ実行
    # workflow_dispatchイベント（手動実行）の場合は常に実行
    if: >-
      github.event_name == 'workflow_dispatch' || 
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    permissions:
      packages: read
      actions: read

    steps:
      # GitHub Container Registryにログイン
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # スキャン対象をプル
      - name: Pull Kong Gateway image
        run: |
          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ vars.KONG_VER }}

      # スキャン
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ vars.KONG_VER }}"
          format: "table"
          severity: "CRITICAL,HIGH" # 重要度が「重大」と「高」の脆弱性のみをスキャン
